#
# Makefile for linux/drivers/platform
#

obj-$(CONFIG_X86)		+= x86/
obj-$(CONFIG_MIPS)		+= mips/
obj-$(CONFIG_OLPC)		+= olpc/
obj-$(CONFIG_GOLDFISH)		+= goldfish/
obj-$(CONFIG_CHROME_PLATFORMS)	+= chrome/
obj-$(CONFIG_X86_INTEL_CE)	+= intelce/
obj-$(CONFIG_TANGO2)		+= tango2/
