
obj-$(CONFIG_FBXBRIDGE)	+= fbxbridge.o

fbxbridge-objs := 	fbxbridge_dev.o fbxbridge_forward.o	\
			fbxbridge_local.o fbxbridge_output.o	\
			fbxbridge_utils.o fbxbridge_filter.o	\
			fbxbridge_dhcp.o fbxbridge_fastpath.o

