obj-$(CONFIG_REMOTI)		+= remoti.o
obj-$(CONFIG_REMOTI_GPIO)	+= remoti-gpio.o
obj-$(CONFIG_REMOTI_LEDS)	+= remoti-leds.o
obj-$(CONFIG_REMOTI_USER)	+= remoti-user.o

remoti-objs			:= core.o core-sysfs.o
remoti-gpio-objs		:= gpio.o
remoti-leds-objs		:= leds.o
remoti-user-objs		:= user.o
